package com.automation.tests;

import com.automation.base.BaseTest;
import com.automation.factory.PageObjectFactory;
import com.automation.pages.QaDavePage;
import io.qameta.allure.*;
import org.testng.Assert;
import org.testng.annotations.Test;

/**
 * UI Test for: https://qa-dave.risk.regn.net/OR
 * Auto-generated by AutomationPrompt — add more scenarios as needed.
 */
@Epic("QaDave Web Application")
@Feature("QaDave Homepage")
public class QaDaveTest extends BaseTest {

    @Test(description = "TC_001 - Verify QaDave homepage loads successfully")
    @Story("Page loads")
    @Description("Opens https://qa-dave.risk.regn.net/OR and verifies the page loads with a non-null title.")
    @Severity(SeverityLevel.BLOCKER)
    public void testPageLoads() {
        QaDavePage qaDavePage = PageObjectFactory.createPage(QaDavePage.class, page);

        qaDavePage.open();

        Assert.assertTrue(qaDavePage.isPageLoaded(),
                "Page main content should be visible");
        Assert.assertNotNull(qaDavePage.getTitle(),
                "Page title should not be null");
    }

    @Test(description = "TC_002 - Verify URL contains expected domain")
    @Story("URL validation")
    @Description("Confirms the current URL contains 'qa-dave.risk.regn.net' after navigation.")
    @Severity(SeverityLevel.NORMAL)
    public void testPageUrl() {
        QaDavePage qaDavePage = PageObjectFactory.createPage(QaDavePage.class, page);

        qaDavePage.open();

        Assert.assertTrue(qaDavePage.getUrl().contains("qa-dave.risk.regn.net"),
                "URL should contain 'qa-dave.risk.regn.net'");
    }

    @Test(description = "TC_003 - Verify page title is not empty")
    @Story("Page title")
    @Description("Checks that the browser tab title is a non-empty string.")
    @Severity(SeverityLevel.NORMAL)
    public void testPageTitleNotEmpty() {
        QaDavePage qaDavePage = PageObjectFactory.createPage(QaDavePage.class, page);

        qaDavePage.open();

        String title = qaDavePage.getTitle();
        Assert.assertNotNull(title, "Title must not be null");
        Assert.assertFalse(title.isBlank(), "Title must not be blank");
    }
}
