package com.automation.pages;

import com.automation.base.BasePage;
import com.microsoft.playwright.Page;
import io.qameta.allure.Step;

/**
 * Page Object for: https://qa-dave.risk.regn.net/OR
 * Auto-generated by AutomationPrompt — update locators to match your application.
 */
public class QaDavePage extends BasePage {

    // TODO: replace with real locators from your application
    private static final String HEADER       = "h1";
    private static final String MAIN_CONTENT = "main, #main, #content, body";
    private static final String NAV_MENU     = "nav, [role='navigation']";

    public QaDavePage(Page page) {
        super(page);
    }

    // ── Actions ───────────────────────────────────────────────────────────

    @Step("Open QaDave page: https://qa-dave.risk.regn.net/OR")
    public void open() {
        navigateTo("https://qa-dave.risk.regn.net/OR");
        waitForPageLoad();
    }

    // ── State ─────────────────────────────────────────────────────────────

    @Step("Verify QaDave page has loaded")
    public boolean isPageLoaded() {
        return isVisible(MAIN_CONTENT);
    }

    @Step("Get page title")
    public String getTitle() {
        return getPageTitle();
    }

    @Step("Get current URL")
    public String getUrl() {
        return getCurrentUrl();
    }

    @Step("Get header text")
    public String getHeaderText() {
        return getText(HEADER);
    }

    @Step("Check navigation menu is visible")
    public boolean isNavVisible() {
        return isVisible(NAV_MENU);
    }
}
